### ISSUE TITLE
Lua packages not immediately available?

### ISSUE THREAD

**Issue by mdietrich16** [BirdeeHub/nixCats-nvim#47] opened 2024-09-21 15:50 UTC
When using [image.nvim](https://github.com/3rd/image.nvim) and opening a [neorg](https://github.com/nvim-neorg/neorg) file directly by `nvim file.norg` (not necessarily containing an image), I get the following error:
```
image.nvim: magick rock not found, please install it and restart your editor. Error: "...ajit2.1-magick-1.6.0-1/share/lua/5.1/magick/wand/lib.lua:206: /nix/store/rhj9b0ssrqnhwbbbplslngq9a1dky8a9-gcc-10.3.0-lib/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /nix/store/0fnb6g07y484cpl191vkf40f3zlfmv64-libjxl-0.10.3/lib/libjxl.so.0.10)"
```
This does not happen when opening the file from a started neovim instance, as the dependencies (`magick` and `imagemagick`) are installed as `extraLuaPackages` and `lspAndRuntimeDeps`, respectively.

**Comment by BirdeeHub** [comment] 2024-09-21 17:11
?????

Just to clarify, you installed magick like so?

```nix
    extraLuaPackages = {
      someCategoryName = [ (lp: with lp; [ magick ]) ];
    };
```

Those are added to $LUA_PATH and $LUA_CPATH for the luajit process that is ran via nix.

This means when it runs luajit, they will already be in the package.path and package.cpath

They should be available well before nvim starts.

I simply combine the functions from the categories by putting them in a new function that passes them all the argument and then merges the resulting lists.

I then pass the resulting function directly to [neovim-unwrapped.lua.withPackages](https://github.com/BirdeeHub/nixCats-nvim/blob/2b455dab0eee7484ce7c956dccda0a7c2111c18b/nix/builder/wrapenvs.nix#L51) and also [set the environment variables](https://github.com/BirdeeHub/nixCats-nvim/blob/2b455dab0eee7484ce7c956dccda0a7c2111c18b/nix/builder/wrapenvs.nix#L69-L72) which is the same thing that [makeNeovimConfig from nixpkgs](https://github.com/NixOS/nixpkgs/blob/9357f4f23713673f310988025d9dc261c20e70c6/pkgs/applications/editors/neovim/utils.nix#L80-L101) does with them

**Comment by BirdeeHub** [comment] 2024-09-21 17:48
```image.nvim: magick rock not found, please install it and restart your editor. Error: "...ajit2.1-magick-1.6.0-1/share/lua/5.1/magick/wand/lib.lua:206: /nix/store/rhj9b0ssrqnhwbbbplslngq9a1dky8a9-gcc-10.3.0-lib/lib
/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /nix/store/0fnb6g07y484cpl191vkf40f3zlfmv64-libjxl-0.10.3/lib/libjxl.so.0.10)"```

This error seems to not be saying that it cant find magick

This error seems to be saying that magick cant find one of its c dependencies, and thus is failing, and thus cant be loaded and thus "magick rock not found" because it failed to load

The error is most likely with the packaging of the magick rock in nixpkgs

(side note, "magick rock" is an amusing phrasing)

**Comment by BirdeeHub** [comment] 2024-09-21 17:59
But yeah its definitely finding the rock. You can see that it knows the path to it in the error you posted.

But it is failing to actually load it properly, but only in norg files, due to a c dependency that seemingly is only missing when you enter a norg file? Very confusing. I have no idea why a norg file would have a different set of c dependencies available to it, compared to any other type of file.

**Comment by BirdeeHub** [comment] 2024-09-21 18:27
I am not convinced that this error is a problem with nixCats yet. It is possible, but feels unlikely given that it is, in fact, finding magick, even when it errors. This error should be present in the programs.neovim module as well.

But there is definitely a problem somewhere.

**Comment by BirdeeHub** [comment] 2024-09-21 19:20
So yeah, conclusion

A, the path to magick is directly patched into image.nvim and you dont need to include it manually.

B. I have no idea why that doesnt work in norg files.

**Comment by BirdeeHub** [comment] 2024-09-21 20:26
```nix
{
  inputs = {
    nixpkgs = {
      url = "github:nixos/nixpkgs/nixpkgs-unstable";
    };
    neovim = {
      url = "github:nix-community/neovim-nightly-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };
  outputs = { nixpkgs, neovim, ...}: let
    forAllSys = nixpkgs.lib.genAttrs nixpkgs.lib.platforms.all;
    overlayMyNeovim = prev: final: {
      myNeovim = let
        luaRC = final.writeText "init.lua" /*lua*/''
          vim.schedule(function()
            vim.cmd("packadd nvim-treesitter");
            require("nvim-treesitter.configs").setup({
              auto_install = false,
              highlight = {
                enable = true
              },
            })
          end)
        '';
      in
      final.wrapNeovim final.neovim {
        configure = {
          customRC = ''lua dofile("${luaRC}")'';
          packages.all.start = with final.vimPlugins; [ 
          ];
          packages.all.opt = with final.vimPlugins; [
            nvim-treesitter.withAllGrammars
          ];
          extraLuaPackages = (lp: with lp; [])
        };
        extraMakeWrapperArgs = ''--prefix PATH : "${final.lib.makeBinPath (with final; [ stdenv.cc.cc ])}"'';
      };
    };
  in 
  {
    packages = forAllSys (system: let
      pkgs = import nixpkgs {
        inherit system;
        overlays = [ overlayMyNeovim ];
      };
      pkgs_nightly = import nixpkgs {
        inherit system;
        overlays = [ neovim.overlays.default overlayMyNeovim ];
      };
      in
      {
        default = pkgs.myNeovim;
        nightly = pkgs_nightly.myNeovim;
      });
  };
}
```

**Comment by BirdeeHub** [comment] 2024-10-22 09:58
Idk why, but its resolved for me now.

Maybe something got fixed upstream but I havent done anything that should or should not fix it XD

Since I can no longer reproduce this issue, I will close it?

If something crops up again, do let me know :)

**Closed by BirdeeHub** 2024-10-22 09:58 UTC
